# Generated by Django 3.2.5 on 2021-07-08 20:07

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=60000)),
                ('is_open', models.BooleanField(default=True)),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_at', models.DateTimeField(default=app.models._60_days_from_now)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=None, null=True)),
                ('text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='required_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
        ),
    ]
