# Generated by Django 3.2.5 on 2021-07-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='chapter',
        ),
        migrations.AddField(
            model_name='lesson',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.college'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
