# Generated by Django 3.2.5 on 2021-07-09 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
